apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdCluster"
metadata:
  name: "example-etcd-cluster"
spec:
  size: 3
  version: "3.1.8"
  pod:
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values: ["etcd"]
              topologyKey: kubernetes.io/hostname
  backup:
    backupIntervalInSecond: 60
    maxBackups: 3
    storageType: "ABS"
    abs:
      absContainer: myabscontainer
      absSecret: abs-credentials
