apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdBackup"
metadata:
  name: example-etcd-cluster-backup
spec:
  clusterName: example-etcd-cluster
  backupIntervalInSecond: 60
  maxBackups: 3
  storageType: "ABS"
  abs:
    path: "myabscontainer/example-cluster.backup"
    absSecret: "abs-credentials"
